---
services:
    db:
        image: pgvector/pgvector:pg17
        env_file: .env
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"',
                ]
            interval: 5s
            timeout: 5s
            retries: 5

    redis:
        image: redis/redis-stack:7.4.0-v8
        ports:
            - 8001:8001
            - 6379:6379
        volumes:
            - redis_data:/data
        environment:
            REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: runtime
        ports:
            - "9000:8000"
        env_file: .env
        depends_on:
            #db:
            #    condition: service_healthy
            redis:
                condition: service_healthy
        command:
            [
                "uv",
                "run",
                "uvicorn",
                "app.main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
            ]

    worker:
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: runtime
        env_file: .env
        depends_on:
            #db:
            #    condition: service_healthy
            redis:
                condition: service_healthy
        command:
            [
                "uv",
                "run",
                "celery",
                "-A",
                "app.worker",
                "worker",
                "--loglevel=info",
            ]

volumes:
    pgdata:
    redis_data:
