"""adding database Trigger

Revision ID: 4a052b179d39
Revises: f9dbf22331dc
Create Date: 2025-11-30 18:34:09.608237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a052b179d39'
down_revision: Union[str, Sequence[str], None] = 'f9dbf22331dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_documents_embedding_hnsw'), table_name='documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
    
    # Add the email column to the users table
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address, synced from auth.users."))
    op.create_unique_constraint('uq_users_email', 'users', ['email'])

    # Create the function to handle new user creation
    op.execute("""
    CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS TRIGGER AS $$
    DECLARE
        new_tenant_id UUID;
    BEGIN
        -- Create a new tenant for the new user
        INSERT INTO public.tenants (name)
        VALUES ('Workspace of ' || NEW.email)
        RETURNING id INTO new_tenant_id;

        -- Create a corresponding user in the public.users table
        INSERT INTO public.users (id, tenant_id, email, role)
        VALUES (NEW.id, new_tenant_id, NEW.email, 'ADMIN');

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
    """)

    # Create the trigger on the auth.users table
    op.execute("""
    CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the trigger and the function in reverse order of creation
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user();")

    # Drop the email column and its constraint
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_column('users', 'email')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_documents_embedding_hnsw'), 'documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
