"""adding allowed domain column

Revision ID: d3047c331038
Revises: 7431516c2bed
Create Date: 2025-12-10 11:23:28.208289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3047c331038'
down_revision: Union[str, Sequence[str], None] = '7431516c2bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('allowed_domains', sa.ARRAY(sa.String()), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'allowed_domains')
    # ### end Alembic commands ###
