"""adding column name to the table user

Revision ID: 480358558f87
Revises: d255f1560a49
Create Date: 2026-05-11 11:29:47.408046

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "480358558f87"
down_revision: Union[str, Sequence[str], None] = "d255f1560a49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=True,
            comment="User's full name, synced from auth.users.",
        ),
    )
    op.execute("UPDATE users SET name = email WHERE name IS NULL")
    op.alter_column("users", "name", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")

    # ### end Alembic commands ###
