"""Node for retrieving relevant documents from the vector store."""

from typing import Optional

from langchain_postgres import PGEngine, PGVectorStore

from app.agent.state import AgentState
from app.services.embeddings import get_embedding_model
from app.settings import settings
from app.utils.logging_config import logger

# 1. Initialize the engine, which will be used at startup.
pg_engine = PGEngine.from_connection_string(url=str(settings.DATABASE_URL))

# 2. A placeholder for the vector store, to be initialized at application startup.
# This avoids re-creating the store on every request.
vector_store: Optional[PGVectorStore] = None


async def retrieve_documents(state: AgentState) -> dict:
    """
    Retrieve relevant documents based on the rephrased question.

    This node uses the standalone question generated by the contextualizer
    to perform a similarity search in the vector store.

    Args:
        state (AgentState): The current state of the agent.

    Returns:
        dict: A dictionary with the updated documents list.
    """
    logger.info("---NODE: RETRIEVE DOCUMENTS---")

    try:
        if vector_store is None:
            raise RuntimeError(
                "Vector store has not been initialized. "
                "Please ensure the application startup logic is correct."
            )

        rephrased_question = state["rephrased_question"]
        if not rephrased_question:
            raise ValueError("Rephrased question is not set in the state.")

        logger.info(f"Retrieving documents for: {rephrased_question}")

        # Perform similarity search with tenant filtering
        retrieved_docs = await vector_store.asimilarity_search(
            rephrased_question,
            k=settings.MAX_RETRIEVED_DOCS,
            filter={"tenant_id": state["tenant_id"]},
        )

        logger.info(f"Retrieved {len(retrieved_docs)} documents")
        return {"documents": retrieved_docs}

    except Exception as e:
        logger.error(f"Error in retrieve_documents: {e}", exc_info=True)
        # Return empty documents list to allow graceful degradation
        return {"documents": []}
